import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {seed,mutate,catalog} from './domain.mjs';
import {DemoStore} from './store.mjs';
import {createApp} from './index.mjs';
const user={id:'u1',name:'Cliente',role:'user'},employee={id:'e1',name:'Empleado',role:'employee'},admin={id:'a1',name:'Admin',role:'admin'};
const reserve={productId:'hass-1',kg:20,pickup:'2099-10-05'};
test('reservas fijan precio y no venden stock inmaduro',()=>{const s=seed(),r=mutate(s,user,'reserve',reserve);assert.equal(r.total,70000);mutate(s,employee,'price',{id:'hass-1',price:4000});assert.equal(r.total,70000);assert.equal(catalog(s)[0].available,160);assert.throws(()=>mutate(s,user,'reserve',{...reserve,productId:'hass-2'}),/suficientes/);assert.throws(()=>mutate(s,user,'reserve',{...reserve,kg:-1}),/Cantidad/);});
test('empleado puede ingresar y cambiar precios pero no corregir ni retirar',()=>{const s=seed();mutate(s,employee,'lot',{productId:'hass-2',kg:10,fridge:'R3',entered:'2026-10-01',ready:'2026-10-03',stage:'Lista para venta'});assert.equal(catalog(s)[1].available,10);for(const kind of ['archive','product','lot-edit','invoice-void'])assert.throws(()=>mutate(s,employee,kind,{}),e=>e.status===403);assert.throws(()=>mutate(s,user,'price',{id:'hass-1',price:900}),e=>e.status===403)});
test('retirar descuenta kilos y cancelar libera reserva sin duplicar',()=>{const s=seed(),r=mutate(s,user,'reserve',reserve);mutate(s,employee,'pickup',{id:r.id,status:'Retirada y pagada'});assert.equal(s.lots[0].kg,160);assert.equal(s.lots[0].reserved,0);assert.throws(()=>mutate(s,admin,'pickup',{id:r.id,status:'Cancelada'}),e=>e.status===409);const r2=mutate(s,user,'reserve',reserve);mutate(s,employee,'pickup',{id:r2.id,status:'Cancelada'});assert.equal(s.lots[0].kg,160);assert.equal(s.lots[0].reserved,0)});
test('facturas conservan originales, impiden duplicados y auditan anulación',()=>{const s=seed(),b={number:'001',supplier:'Proveedor',issued:'2026-10-01',total:90000,file:Buffer.from('%PDF-1.4 example').toString('base64')};const r=mutate(s,employee,'invoice',b);assert.throws(()=>mutate(s,employee,'invoice',b),e=>e.status===409);mutate(s,admin,'invoice-void',{id:r.id,reason:'Error de registro'});assert.equal(s.invoices[0].file,b.file);assert.equal(s.audit[0].details.reason,'Error de registro')});
test('API protege inventario, limita reservas al propietario y serializa concurrentes',async()=>{const dir=await mkdtemp(join(tmpdir(),'hecopal-'));const store=new DemoStore(join(dir,'state.json'));const server=createApp({store}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url='http://127.0.0.1:'+server.address().port;
 const api=(path,token,body)=>fetch(url+'/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});
 try{assert.equal((await api('workspace')).status,403);const {token}=await (await api('demo-session',null,{role:'user'})).json();assert.equal((await api('workspace',token)).status,403);const results=await Promise.all([api('actions/reserve',token,{...reserve,kg:150}),api('actions/reserve',token,{...reserve,kg:150})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal((await store.read()).lots[0].reserved,150);const other={...user,id:'other'};await store.transaction(s=>mutate(s,other,'reserve',{...reserve,kg:10}));const own=await (await api('reservations',token)).json();assert.equal(own.length,1);assert.equal(own[0].userId,'demo-user');assert.equal((await api('actions/archive',token,{id:'hass-1'})).status,403)}finally{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true})}
});

test('kilos decimales se reservan sin errores de redondeo',()=>{const s=seed();s.lots[0].kg=0.3;for(let i=0;i<3;i++)mutate(s,user,'reserve',{...reserve,kg:0.1});assert.equal(s.lots[0].reserved,0.3);assert.equal(catalog(s)[0].available,0);assert.throws(()=>mutate(s,user,'reserve',{...reserve,kg:0.01}),e=>e.status===409)});
